### PR TITLE
Add support for the "*" wildcard in options

### PR DESCRIPTION
**Pull request by gilvegliach**
This commit adds support for the `*` wildcard in the list of urls in the options. For example, one can write:

```
https://*.domain.com
```

### CODE REVIEW

**Comment by hjacobs** [comment]
@gilvegliach is this fast enough (every request including assets etc will be affected)?

**Comment by gilvegliach** [comment]
@hjacobs I haven't seen any performance difference in practice.

**Comment by zd0** [comment]
Side note: there is a [filter parameter](https://developer.chrome.com/extensions/webRequest#type-RequestFilter) in the `chrome.webRequests` apis: it should allow wildcarding to match host/path. It's not exactly regular expression based, you need to [check documentation](https://developer.chrome.com/extensions/match_patterns) what kind of patterns are allowed.
The good thing, that the filter is more safe and aware about host/path parts of url. So you shouldn't have "security leaks" when you send access token to some url with matching host in path or query part.

**Comment by gilvegliach** [comment]
@zd0 @hjacobs Reimplemented with url filters. Example wildcard:

```
https://*.domain.org/*
```

**Comment by LappleApple** [comment]
@hjacobs Hey, any reason why @gilvegliach's PR remains outstanding? :) (and are you maintaining this project now?)

**Comment by elgalu** [comment]
Awesome!! FYI is important to add `/*` at the end else it didn't work in all cases for me.

works:
```
https://*.domain.com/*
```

doesn't:
```
https://*.domain.com
```

**Comment by gilvegliach** [comment]
@elgalu True. I put a link to the docs on the label "Url patterns" in the settings (note it is blue now). Some people are still confused though, so I think I'll add some examples in the README.

**Pull request merged**
